version: "3"
services:
  give-me-some-credit:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: give-me-some-credit
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ../:/home/jovyan/work
    command: /opt/conda/bin/jupyter notebook --ip='0.0.0.0' --port=8888 --no-browser --allow-root
    env_file:
      - auth.env